apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: nginx-tls-cert

spec:
  secretName: nginx-tls-cert

  commonName: nginx.treichels.net

  dnsNames:
    - nginx.treichels.net

  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
