apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx

spec:
  ingressClassName: traefik

  rules:
  - host: nginx-ingress.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
