apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx-external

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  tls:
    - hosts:
        - nginx.treichels.net
      secretName: nginx-ext-cert

  rules:
    - host: nginx.treichels.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx-internal

  annotations:
    cert-manager.io/cluster-issuer: my-ca

spec:
  tls:
    - hosts:
        - nginx.lan
        - nginx-lb.lan
      secretName: nginx-int-cert

  rules:
    - host: nginx.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: https
