apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      app.kubernetes.io/name: nginx

resources:
#- deployment.yaml
#- service.yaml
#- ingress.yaml
- config.yaml
- data.yaml
- cert.yaml
- kservice.yaml
