apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: nginx-treichels-net

spec:
  secretName: nginx-treichels-net
  commonName: nginx.treichels.net

  dnsNames:
    - nginx.treichels.net

  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
